spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/member/**
        - id: auth-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: board-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/board/**
        - id: comment-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/comment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
